In [11]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

from pathlib import Path
from datetime import datetime
from time import perf_counter

import numpy as np
import pandas as pd


import plotly.offline as pyoff
import plotly.graph_objs as go
from plotly import tools
import plotly.express as px

import cufflinks as cf
cf.go_offline()

import day_8 as d8


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
def get_data(day):
    folder = Path("input")

    with open(folder / f"day_{day}.txt", "r") as f:
        data = f.read().splitlines()

    return data


## Day 7

In [186]:
d8.d10_p1()

6867.0

In [136]:
data = get_data(10)

In [152]:

o_i_positions ={
    "top": (-1, 0),
    "right": (0, 1),
    "bottom": (1, 0),
    "left": (0, -1)
}
following_o_i = {
    # "-" : {
    #     # (direction from, position), position to
    #     (0, 1, "top"): "right", # moving from top to right
    #     (0, 1, "bottom"): "left", # moving from top to right 
    #     (0, -1, "top"): "left", # moving top bottom to left - 7, J
    #     (0, -1, "bottom"): "left", # moving top bottom to left - 7, J
    # },
    # (direction from, position), position to
    ("7", "top"): "right",
    ("J", "top"): "right",
    ("7", "bottom"): "right",
    ("J", "bottom"): "right",

    ("F", "top"): "left",
    ("L", "top"): "left",
    ("F", "bottom"): "left",
    ("L", "bottom"): "left",
    # (("7", "J"), "top"): "right", # moving from top to right
    # (("7", "J"), "bottom"): "left", # moving from top to right 
    # (("F", "L"), "top"): "left", # moving top bottom to left - 7, J
    # (("F", "L"), "bottom"): "left", # moving top bottom to left - 7, J

    ("7", "left"): "bottom",
    ("L", "left"): "bottom",
    ("7", "right"): "top",
    ("L", "right"): "top",

    ("F", "left"): "top",
    ("J", "left"): "top",
    ("F", "right"): "bottom",
    ("J", "right"): "bottom",
    # (direction from, position), position to
    # (("F", "J"), "left"): "top", # moving from left to top  - going up and F or going down and J
    # (("F", "J"), "right"): "bottom", # moving from right to bottom - going up and F or going down and J
    # (("7", "L"), "left"): "bottom", # moving from left to top  - going up and F
    # (("7", "L"), "right"): "top", # moving from right to bottom - going up and F
}


In [153]:
directions, allowed_directions = d8.get_directions()

In [177]:
data = [
    "...........",
".F-------7.",
".|F-----7|.",
".||.....||.",
".||.....||.",
".|L-7.F-J|.",
".|..|.|..|.",
".S--J.L--J.",
"..........."
]

In [178]:
# data = get_data(10)

data_array, np_o_i = d8.initialize_np_o_i(data)

np_o_i = d8.find_o_from_corners(np_o_i)

initial_start_row, initial_start_col = np.where(data_array == 'S')

# data_array[initial_start_row[0] - 1: initial_start_row[0] + 2, initial_start_col[0] - 1: initial_start_col[0] + 2]
data_array[initial_start_row[0], initial_start_col[0]] = "L"

# getting the top left corner
start_row = np.where(np_o_i == 1)[0][0]
start_col = np.where(np_o_i == 1)[1][0]

assert data_array[start_row, start_col] == "F"

data_array[start_row, start_col] = "S"

start_row, start_col = np.where(data_array == 'S')

32
22


In [179]:
# Next we go down
outside_position = "left"
inside_position = "right"

end_row, end_col = start_row, start_col + 1

s = "F"

In [180]:
# Starting next value

potential_start = []
symbols = []
for (i, j), values in directions.items():
    if data_array[start_row + i, start_col + j] in values:
        potential_start.append((start_row + i, start_col + j))
        symbols.append(data_array[start_row + i, start_col + j])

row, col = potential_start[1]
end_row, end_col = potential_start[0]

prev_i = (row - start_row)[0]
prev_j = (col - start_col)[0]

s = symbols[1][0]

In [181]:
print(prev_i, prev_j)
print(row, col)
print(i, j)
print(s)

1 0
[2] [1]
0 -1
|


In [183]:
data_array

array([['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', 'S', '-', '-', '-', '-', '-', '-', '-', '7', '.'],
       ['.', '|', 'F', '-', '-', '-', '-', '-', '7', '|', '.'],
       ['.', '|', '|', '.', '.', '.', '.', '.', '|', '|', '.'],
       ['.', '|', '|', '.', '.', '.', '.', '.', '|', '|', '.'],
       ['.', '|', 'L', '-', '7', '.', 'F', '-', 'J', '|', '.'],
       ['.', '|', '.', '.', '|', '.', '|', '.', '.', '|', '.'],
       ['.', 'L', '-', '-', 'J', '.', 'L', '-', '-', 'J', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']],
      dtype='<U1')

In [182]:
np_o_i

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [2., 1., 1., 0., 0., 0., 0., 0., 1., 1., 2.],
       [2., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [2., 1., 0., 0., 1., 0., 1., 0., 0., 1., 2.],
       [2., 1., 1., 1., 1., 0., 1., 1., 1., 1., 2.],
       [2., 2., 2., 0., 2., 0., 2., 0., 2., 2., 2.]])

In [184]:
end_of_loop = False

while not end_of_loop:
    i, j = allowed_directions[(s, prev_i, prev_j)]
    if s in ["|", "-"]:
        print(s, outside_position, inside_position)
        outsive_row, outside_col = row + o_i_positions[outside_position][0], col + o_i_positions[outside_position][1]
        inside_row, inside_col = row + o_i_positions[inside_position][0], col + o_i_positions[inside_position][1]

        print(np_o_i[outsive_row, outside_col][0])
        print(np_o_i[inside_row, inside_col][0])

        if np_o_i[outsive_row, outside_col][0] == 0:
            np_o_i[outsive_row, outside_col] = 2
        elif np_o_i[outsive_row, outside_col] == 3:
            print("error")
        
        if np_o_i[inside_row, inside_col] == 0:
            np_o_i[inside_row, inside_col] = 3
        elif np_o_i[inside_row, inside_col] == 2:
            print("error")
    else:
        # Change of position
        outside_position = following_o_i[(s, outside_position)]
        inside_position = following_o_i[(s, inside_position)]

    # Next symbol
    row += i
    col += j
    s = data_array[row, col][0]

    if row == end_row and col == end_col:
        end_of_loop = True
    else:
        prev_i, prev_j = i, j

| left right
2.0
1.0
| left right
2.0
1.0
| left right
2.0
1.0
| left right
2.0
1.0
| left right
2.0
0.0
- bottom top
2.0
3.0
- bottom top
0.0
0.0
| right right
0.0
0.0
error
- top top
0.0
0.0
error
| left left
1.0
1.0
| left left
1.0
1.0
- top top
1.0
1.0
- top top
1.0
1.0
- top top
1.0
1.0
- top top
1.0
1.0
- top top
1.0
1.0
| right right
1.0
1.0
| right right
1.0
1.0
- bottom bottom
0.0
0.0
error
| left left
2.0
2.0
error
- bottom bottom
0.0
0.0
error
- bottom bottom
2.0
2.0
error
| right right
2.0
2.0
error
| right right
0.0
0.0
error
| right right
2.0
2.0
error
| right right
0.0
0.0
error
| right right
2.0
2.0
error
- top top
2.0
2.0
error
- top top
2.0
2.0
error
- top top
2.0
2.0
error
- top top
2.0
2.0
error
- top top
2.0
2.0
error
- top top
2.0
2.0
error


In [185]:
np_o_i

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 0., 0., 0., 0., 0., 1., 1., 2.],
       [2., 1., 1., 2., 0., 0., 0., 0., 1., 1., 2.],
       [2., 1., 1., 1., 1., 0., 1., 1., 1., 1., 2.],
       [2., 1., 3., 3., 1., 2., 1., 2., 0., 1., 2.],
       [2., 1., 1., 1., 1., 0., 1., 1., 1., 1., 2.],
       [2., 2., 2., 2., 2., 0., 2., 2., 2., 2., 2.]])

In [160]:
print(len(np.where(np_o_i == 0)[0]))

4046


In [161]:

for a in range(50):
    print(a, len(np.where(np_o_i == 0)[0]))
    for i in range(np_o_i.shape[0]):
        for j in range(np_o_i.shape[1]):
            
            for k in [2, 3]:
                if np_o_i[i, j] == k:

                    # change the value of all the cells around
                    if j > 0:
                        if np_o_i[i, j - 1] == 0:
                            np_o_i[i, j - 1] = k

                    if i > 0:
                        if np_o_i[i - 1, j] == 0:
                            np_o_i[i - 1, j] = k

                    if j < np_o_i.shape[1] - 1:
                        if np_o_i[i, j + 1] == 0:
                            np_o_i[i, j + 1] = k
                    
                    if i < np_o_i.shape[0] - 1:
                        if np_o_i[i + 1, j] == 0:
                            np_o_i[i + 1, j] = k
    
    
    if len(np.where(np_o_i == 0)[0]) == 0:
        break

0 4046
1 249
2 214
3 206
4 204
5 204
6 204
7 204
8 204
9 204
10 204
11 204
12 204
13 204
14 204
15 204
16 204
17 204
18 204
19 204
20 204
21 204
22 204
23 204
24 204
25 204
26 204
27 204
28 204
29 204
30 204
31 204
32 204
33 204
34 204
35 204
36 204
37 204
38 204
39 204
40 204
41 204
42 204
43 204
44 204
45 204
46 204
47 204
48 204
49 204


In [168]:
len(np.where(np_o_i == 2)[0])

5662

In [ ]:
# potential_start = []
# symbols = []
# for (i, j), values in directions.items():
#     if data_array[start_row + i, start_col + j] in values:
#         potential_start.append((start_row + i, start_col + j))
#         symbols.append(data_array[start_row + i, start_col + j])

# row, col = potential_start[0]
# end_row, end_col = potential_start[1]

prev_i = (row - start_row)[0]
prev_j = (col - start_col)[0]

s = symbols[0][0]

end_of_loop = False

while not end_of_loop:
    # current symbol
    i, j = allowed_directions[(s, prev_i, prev_j)]

    if s == "|":
        left_pos = (row, col - 1)
        right_pos = (row, col + 1)

        left_value = np_o_i[left_pos][0]
        right_value = np_o_i[right_pos][0]

        if set([left_value, right_value]) == set([2, 3]):
            pass
        elif (set([left_value, right_value]) == set([2, 2])) or (set([left_value, right_value]) == set([3, 3])):
            print("Error")
        elif left_value == 2:
            np_o_i[right_pos] = 3
        elif right_value == 2:
            np_o_i[left_pos] = 3
        elif left_value == 3:
            np_o_i[right_pos] = 2
        elif right_value == 3:
            np_o_i[left_pos] = 2
        
        # print(left_value, right_value)
    elif s == "-":
        top_pos = (row - 1, col)
        bottom_pos = (row + 1, col)

        top_value = np_o_i[top_pos][0]
        bottom_value = np_o_i[bottom_pos][0]

        if set([top_value, bottom_value]) == set([2, 3]):
            pass
        elif (set([top_value, bottom_value]) == set([2, 2])) or (set([top_value, bottom_value]) == set([3, 3])):
            print("Error")
        elif top_value == 2:
            np_o_i[bottom_pos] = 3
        elif bottom_value == 2:
            np_o_i[top_pos] = 3
        elif top_value == 3:
            np_o_i[bottom_pos] = 2
        elif bottom_value == 3:
            np_o_i[top_pos] = 2
    
    # next symbol
    row += i
    col += j
    s = data_array[row, col][0]
    np_o_i[row, col] = 1
    counter += 1

    if row == end_row and col == end_col:
        end_of_loop = True
    else:
        prev_i, prev_j = i, j


In [36]:
# data_array[start_row - 2: start_row + 3, start_col - 2: start_col + 3]
# np_o_i[start_row - 2: start_row + 3, start_col - 2: start_col + 3]

array([['|', 'L', '-', '.', 'F'],
       ['|', 'F', '.', 'F', '7'],
       ['7', 'F', 'F', '7', '-'],
       ['7', 'F', 'J', 'L', '7'],
       ['|', '|', 'F', '-', 'J']], dtype='<U1')

In [37]:
np_o_i[start_row - 2: start_row + 3, start_col - 2: start_col + 3]

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 0: unkonwn
# 1: in loop
# 2: outside loop
# 3: inside loop

In [329]:
for b in range(100):
    print("b", b, len(np.where(np_o_i == 0)[0]))
    start_row, start_col = np.where(data_array == 'S')

    potential_start = []
    symbols = []
    for (i, j), values in directions.items():
        if data_array[start_row + i, start_col + j] in values:
            potential_start.append((start_row + i, start_col + j))
            symbols.append(data_array[start_row + i, start_col + j])

    row, col = potential_start[0]
    end_row, end_col = potential_start[1]

    prev_i = (row - start_row)[0]
    prev_j = (col - start_col)[0]

    s = symbols[0][0]

    end_of_loop = False

    while not end_of_loop:
        # current symbol
        i, j = allowed_directions[(s, prev_i, prev_j)]

        if s == "|":
            left_pos = (row, col - 1)
            right_pos = (row, col + 1)

            left_value = np_o_i[left_pos][0]
            right_value = np_o_i[right_pos][0]

            if set([left_value, right_value]) == set([2, 3]):
                pass
            elif (set([left_value, right_value]) == set([2, 2])) or (set([left_value, right_value]) == set([3, 3])):
                print("Error")
            elif left_value == 2:
                np_o_i[right_pos] = 3
            elif right_value == 2:
                np_o_i[left_pos] = 3
            elif left_value == 3:
                np_o_i[right_pos] = 2
            elif right_value == 3:
                np_o_i[left_pos] = 2
            
            # print(left_value, right_value)
        elif s == "-":
            top_pos = (row - 1, col)
            bottom_pos = (row + 1, col)

            top_value = np_o_i[top_pos][0]
            bottom_value = np_o_i[bottom_pos][0]

            if set([top_value, bottom_value]) == set([2, 3]):
                pass
            elif (set([top_value, bottom_value]) == set([2, 2])) or (set([top_value, bottom_value]) == set([3, 3])):
                print("Error")
            elif top_value == 2:
                np_o_i[bottom_pos] = 3
            elif bottom_value == 2:
                np_o_i[top_pos] = 3
            elif top_value == 3:
                np_o_i[bottom_pos] = 2
            elif bottom_value == 3:
                np_o_i[top_pos] = 2
        # next symbol
        row += i
        col += j
        s = data_array[row, col][0]
        np_o_i[row, col] = 1
        counter += 1

        if row == end_row and col == end_col:
            end_of_loop = True
        else:
            prev_i, prev_j = i, j

    for a in range(50):
        for i in range(np_o_i.shape[0]):
            for j in range(np_o_i.shape[1]):
                
                for k in [2, 3]:
                    if np_o_i[i, j] == k:

                        # change the value of all the cells around
                        if j > 0:
                            if np_o_i[i, j - 1] == 0:
                                np_o_i[i, j - 1] = k

                        if i > 0:
                            if np_o_i[i - 1, j] == 0:
                                np_o_i[i - 1, j] = k

                        if j < np_o_i.shape[1] - 1:
                            if np_o_i[i, j + 1] == 0:
                                np_o_i[i, j + 1] = k
                        
                        if i < np_o_i.shape[0] - 1:
                            if np_o_i[i + 1, j] == 0:
                                np_o_i[i + 1, j] = k
        
        
        if len(np.where(np_o_i == 0)[0]) == 0:
            break

b 0 4365
b 1 858
b 2 855
Error
b 3 853
Error
b 4 853
Error
Error
b 5 853
Error
Error
b 6 853
Error
Error
b 7 853
Error
Error
b 8 853
Error
Error
b 9 853
Error
Error
b 10 853
Error
Error
b 11 853
Error
Error
b 12 853
Error
Error
b 13 853
Error
Error
b 14 853
Error
Error
b 15 853
Error
Error
b 16 853
Error
Error
b 17 853
Error
Error


KeyboardInterrupt: 

854
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853
853


In [ ]:
np.where(np_o_i == 3)

(array([133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 134,
        134, 134, 134, 134, 134, 134, 134, 134, 134, 134, 134, 134, 134,
        134, 134, 134, 134, 134, 134, 134, 135, 135, 135, 135, 135, 135,
        135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135,
        135, 135, 135, 135, 135], dtype=int64),
 array([56, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 54, 55, 56, 61, 62,
        63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 54,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78], dtype=int64))

In [ ]:
len(np.where(np_o_i == 0)[0])

857

In [ ]:
np.savetxt('my_array.txt', np_o_i, delimiter=',', fmt='%d')
